services:
  web:
    build: .
    image: dj-weather
    container_name: dj-weather
    ports:
      - "8160:8000"
    environment:
      SQLITE_PATH: /app/db/db.sqlite3
      STATIC_ROOT: /app/static
    volumes:
      - ./data/sqlite:/app/db
      - ./data/static:/app/static
